// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CategoriesController from "./categories_controller"
application.register("categories", CategoriesController)

import DataTablesController from "./dataTables_controller"
application.register("dataTables", DataTablesController)

import OcrController from "./ocr_controller"
application.register("ocr", OcrController)
